version: '3.8'

services:
  app:
    image: ghcr.io/eth-global-cannes/backend:latest
    ports:
      - "8000:8000"
    environment:
      - API_KEY=${API_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - MCP_SERVER_URL=${MCP_SERVER_URL}
    restart: unless-stopped