name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Log in to GHCR
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build and push Docker image
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository }}
        TAG=latest
        docker build -t $IMAGE_ID:$TAG .
        docker push $IMAGE_ID:$TAG